### ISSUE TITLE
Weird polylines

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#100]
berlin_karl_marx_allee.osm

street.id = 514
section.id = 384 and section.id = 389

Those sections build a triangle.

![image](https://github.com/prochitecture/blosm/assets/613295/a82446fb-61eb-4db9-9258-0b9debc8fde0)

I moved the points on the sides closer to the point in the middle for clarity.

The same problem for:
street.id = 506
section.id = 190 and section.id = 194

**Comment by polarkernel** [comment]
> Those sections build a triangle.

Bug fixed and committed.

**Comment by vvoovv** [comment]
Thanks
