### ISSUE TITLE
A change in the data structure for intersections

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#101]
Suppose a `street` enters an `intersection`:
```python
street.succ is intersection
```

I want to get a street on the left from `street` and a street on the right from `street`, that are also attached to the `intersection`
```python
streetL.succ is intersection or streetL.pred is intersection
streetR.succ is intersection or streetR.pred is intersection
```

I suggest setting `street.succ` or `street.pred` to an instance of the class `IntConnector`. Then it will be quite straightforward to get `streetL` or `streetR`:
```python
streetL = street.succ.pred.item
streetR = street.succ.succ.item
```

**Comment by polarkernel** [comment]
> I suggest setting `street.succ` or `street.pred` to an instance of the class `IntConnector`.

Implemented and committed.

Note that the `Section` instances remain untrimmed at the connectors. The intersection area is still computed, although this will eventually be done by GNs. I will clean up the code once we are in a more stable state.

**Comment by vvoovv** [comment]
Thanks.

Anyway, overlapping intersections will require a special processing in the code.
