### ISSUE TITLE
Curvy facades

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#17]
Classification of curvy facades produces odd results:

(bern_old_town.osm, Kirche St. Peter und Paul):
![image](https://user-images.githubusercontent.com/613295/119490793-eb2eee00-bd65-11eb-899c-297a5c03765d.png)

**Comment by vvoovv** [comment]
(bern_old_town.osm, Kirche St. Peter und Paul):

![image](https://user-images.githubusercontent.com/613295/119490953-131e5180-bd66-11eb-9dca-05d34e50cd80.png)

**Comment by vvoovv** [comment]
I suggest skipping curvy facades from from the visibility and classification calculations.

**Comment by vvoovv** [comment]
How to define a curvy facade?

A curvy facade is a sequence of narrow facades connecting each other "smoothly".

**Comment by polarkernel** [comment]
> A curvy facade is a sequence of narrow facades connecting each other "smoothly".

Are we back to apse detection (see https://github.com/prochitecture/bpypolyskel/issues/5#issuecomment-756781170)?

**Comment by vvoovv** [comment]
> > A curvy facade is a sequence of narrow facades connecting each other "smoothly".
> 
> Are we back to apse detection (see [prochitecture/bpypolyskel#5 (comment)](https://github.com/prochitecture/bpypolyskel/issues/5#issuecomment-756781170))?

A curvy facade can have an arbitrary shape.

**Comment by vvoovv** [comment]
> I suggest skipping curvy facades from from the visibility and classification calculations.

That was the wrong idea.

A front part must be still detected to place an entrance. For example, suppose we have a building with a circular footprint (it could be an ancient tower). It still needs an entrance.

**Comment by vvoovv** [comment]
Curvy sequences can be also concave. [Example](https://www.openstreetmap.org/#map=18/55.82233/37.64587).

**Comment by vvoovv** [comment]
A curvy sequence must be classified if
1) there is no entrance tagged in OSM for all edges
AND
2) there are no wide edges classified as the front facades

One approach would be to connect the first and the last node of the curve sequence with a straight line and use that proxy edge for the visibility calculation and classification. But how would it work for a concave sequence if a way follows the concave sequence and is located very close to the concave sequence?

**Comment by vvoovv** [comment]
A special case is a completely curvy building. Example: a circular footprint.

**Comment by vvoovv** [comment]
> Are we back to apse detection (see [prochitecture/bpypolyskel#5 (comment)](https://github.com/prochitecture/bpypolyskel/issues/5#issuecomment-756781170))?

The apse detection and the detection of other patterns will required to generate realistic models of churches and cathedrals.

**Comment by vvoovv** [comment]
Many stadiums have curvy footprint.

**Comment by vvoovv** [comment]
Joined with #16.
