### ISSUE TITLE
Possible conversion of action/facade_visibility.py and action/facade_classification.py to mathutils.

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#19]
_numpy_ is very slow in linear algebra for 2D and 3D vectors in comparison to _mathutils_.

I suggest discussing here if it makes sense to convert _action/facade_visibility.py_ and _action/facade_classification.py_ to _mathutils_.

**Comment by polarkernel** [comment]
> numpy is very slow in linear algebra for 2D and 3D vectors in comparison to mathutils.

This is not true for all cases. I introduced _numpy_ in _facade_visibility.py_ mainly to compute the transform of many vertices to the way-segment coordinate system, which is done for every way-segment (line [136 ](https://github.com/prochitecture/blosm/blob/ac91b304db9e68e2cb794c76e0129937eee13c0b/action/facade_visibility.py#L136)in currnt code).  This uses a multiplication of a large block (hundreds to  thousands) of vectors with a transform matrix. This is the case _numpy_ is made for. The following test shows an example for 500 vertices:

```Python
v_np = np.random.rand(500,2)
v_mu = [mathutils.Vector(v_np[i,:]) for i in range(v_np.shape[0])]

u = mathutils.Vector((2.0,5.0)).normalized()
matrix_np = np.array(( (u[0], -u[1]), (u[1], u[0]) ))
matrix_mu = mathutils.Matrix( [[u[0], -u[1]], [u[1], u[0]] ])

print( 'mathutils:',timeit.timeit("trsf1 = [ [v @ matrix_mu] for v in v_mu ]", number=10000, globals=globals()) )
print( 'numpy:    ',timeit.timeit("trsf = np.matmul(v_np, matrix_np, out=v_np)", number=10000, globals=globals()) )

> mathutils: 0.8947755
> numpy:     0.0564952
```
In the rest of the code, there are no computations of magnitudes, unit vectors, cross-products and so on, which are slow in _numpy_. Just element accesses, comparisons and basic arithmetic. I don't know whether we would win a lot introducing _mathutils.Vector_'s.

**Comment by vvoovv** [comment]
Then _mathutils_ and _numpy_ must coexist peacefully. I'll review how they interact with each other.

**Comment by vvoovv** [comment]
I am currently integrating the code to detect features. A note I have is that a feature class should be an attribute of _BldgVector_ rather than _BldgEdge_. A shared edge can be a part of the curved feature for a building and a part of the rectangular one for the other building. I'll implement that in the course of the integration.

**Comment by polarkernel** [comment]
> A shared edge can be a part of the curved feature for a building and a part of the rectangular one for the other building. I'll implement that in the course of the integration.

All these hidden details of OSM, we will never end!!!!     :-)

**Comment by vvoovv** [comment]
Actually I wanted to post my last message at #16 :)
