### ISSUE TITLE
[GN] General principles of operation of the addon and Geometry Nodes

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#37]
I've just started to learn Geometry Nodes. So my knowledge about them is limited at the moment.

Here is my current understanding. The task is to instance different Blender objects representing facade and roof parts on generated vertices. So each vertex corresponds to a specific instance of a Blender object. The instance must be rotated and scaled accordingly.

![image](https://user-images.githubusercontent.com/613295/158450049-a7d1c97e-d66a-4db5-80ab-a852db8dfa69.png)

But where to get the values for the rotation and scale of the instance in question?

Also there is a need to somehow indicated which Blender object should be instanced at the given vertex.

I suggest to pass that information as attributes of vertices:
* rotation_z
* scale_x
* scale_y
* scale_z
* instance_index (interger) or instance class (string)

I haven't tested yet if this approach would work.

**Comment by Tar0x** [comment]
You can get the rotaion from the instancer geometry for example (eg. normal) or tangent from a curve. Actually my current setup handles this automatically based on the suplpied 2D shape generated by the OSM addon. 

Currently the system also handles scaling of instances to fit the wall and custom model dimensions that user can set up.
For example if the building has 9.1m long wall and user specify the width of one piece to be 3m, the system instantiates 3 copies and scale them to fit that 0.1m.

Speaking of instances, we have to think of some "folder" system, how modules will be choosed. 
I suggest something similar to this: type of the building > building kit (for example a user can have 3 types of suburban modular kits, each with different wall/pillar/window look) > floor (mostly ground floors will have different modules than other floors and then some gable on top probably) > side (front facades will have different modules than other sides). ...Based on such system will be the instanced model chosen.

**Comment by vvoovv** [comment]
> Here is my current understanding.

Forgot to describe how everything should work at the end.

The addon generates those vertices with the required attributes. Then a Geometry Nodes setup is applied to the generated vertices.

**Comment by vvoovv** [comment]
> You can get the rotaion from the instancer geometry for example (eg. normal) or tangent from a curve. Actually my current setup handles this automatically based on the suplpied 2D shape generated by the OSM addon.

Do you use `arcsine` or `arccosine` geometry nodes to get the angle formed by a normal to an instancer face?

**Comment by vvoovv** [comment]
> Currently the system also handles scaling of instances to fit the wall and custom model dimensions that user can set up. For example if the building has 9.1m long wall and user specify the width of one piece to be 3m, the system instantiates 3 copies and scale them to fit that 0.1m.

How a piece width is set? Is it an input attribute of the GN-setup?

Is it possible to get the width (9.1m in your example) in a GN-setup?

**Comment by vvoovv** [comment]
> Speaking of instances, we have to think of some "folder" system, how modules will be choosed.

I think this is also related to building styling. There is an internal styling system in the addon. It's based on styles defined in a number of text files. I'll create a separate topic for the styling.

**Comment by Tar0x** [comment]
> > You can get the rotaion from the instancer geometry for example (eg. normal) or tangent from a curve. Actually my current setup handles this automatically based on the suplpied 2D shape generated by the OSM addon.
> 
> Do you use `arcsine` or `arccosine` geometry nodes to get the angle formed by a normal to an instancer face?

Actually I generate proxy walls geometry, that transfers orientation to modules.



> > Currently the system also handles scaling of instances to fit the wall and custom model dimensions that user can set up. For example if the building has 9.1m long wall and user specify the width of one piece to be 3m, the system instantiates 3 copies and scale them to fit that 0.1m.
> 
> How a piece width is set? Is it an input attribute of the GN-setup?
> 
> Is it possible to get the width (9.1m in your example) in a GN-setup?

It's customizable via parameter, so user can use modules in any width/height.

**Comment by vvoovv** [comment]
As I mentioned in the neighbor topic, my idea is that the addon generates vertices and writes the required attributes to them. It's the task of the addon to calculate everything. Those vertices with the attributes are used by GN-setup to instance the required modules.

Do you have any objections against this approach?

**Comment by vvoovv** [comment]
> As I mentioned in the neighbor topic, my idea is that the addon generates vertices and writes the required attributes to them. It's the task of the addon to calculate everything. Those vertices with the attributes are used by GN-setup to instance the required modules.

Also the addon can create Blender curves to be used by GN-setups for different purposes.
