### ISSUE TITLE
Getting overlay imagery for matplotlib

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#42]
Progress report. I decoupled downloading and stitching image tiles from Blender. OSM objects can be drawn now over the stitched image.

However something is wrong with the order of rows or columns. It seems to be different with the one in Blender. I have to investigate that.

![image](https://user-images.githubusercontent.com/613295/168023119-31e25409-23d8-41dc-8ec3-aa89aa81ebfa.png)

**Comment by vvoovv** [comment]
Commited the code. The new command line arguments can be seen with _--help_. The new command line arguments corresponds to the options for the overlay imagery in Blender.

For example, to get ArcGIS world imagery:
--overlayDir /path/to/folder/where/downloaded/tiles/are/stored
--overlayType arcgis-satellite
--overlayAccessToken ArcGIS_access_token (see [Getting ArcGIS access token](https://github.com/vvoovv/blender-osm/wiki/Getting-ArcGIS-access-token))

Does it work for you?

**Comment by polarkernel** [comment]
> Does it work for you?

10+!! This works great and will be a substantial help on developing street and intersection polygons. Thank you!!

Would it be possible somehow to switch on and off the overlaid drawing of the map objects?

**Comment by vvoovv** [comment]
> Would it be possible somehow to switch on and off the overlaid drawing of the map objects?

Not sure about matplotlib. But that's certainly possible in Blender.

**Comment by polarkernel** [comment]
> Not sure about matplotlib. But that's certainly possible in Blender.

Sorry, I was too vague, I mean the drawings made by _mpl/renderer/*_.

**Comment by vvoovv** [comment]
Do you mean pressing a toggle button to toggle the visibility of OSM objects?

**Comment by polarkernel** [comment]
> Do you mean pressing a toggle button to toggle the visibility of OSM objects?

I'd like just (sometimes) to omit drawing this map and get only the satellite image:

![Namenlos](https://user-images.githubusercontent.com/48180714/168265885-1b872cac-7682-4349-aeb8-a176d20a4aba.png)

Maybe using `--drawMap` or something like this as argument. There's no button required.

**Comment by vvoovv** [comment]
So you want to get satellite imagery only?

**Comment by vvoovv** [comment]
You want to get:
1) OSM objects and satellite imagery
2) Satellite imagery only

Right?

**Comment by polarkernel** [comment]
> You want to get:
    OSM objects and satellite imagery
    Satellite imagery only
Right?

Sorry, was hungry and therefore off for a moment.

Or even better
1) OSM objects only
2) OSM objects and satellite imagery
3) Satellite imagery only

With 1) I can see street/objects collisions, with 2) the way-categories, and with 3) check the shape of crossings and the width of streets. Currently, I can get 1) and 2), but not 3).

**Comment by vvoovv** [comment]
> 3. Satellite imagery only

I'll add this feature later today.

**Comment by vvoovv** [comment]
Added the command line argument `--showOverlayOnly`.

**Comment by polarkernel** [comment]
> Added the command line argument --showOverlayOnly.

The satellite image is fine, but I can't draw any more my overlays.

**Comment by vvoovv** [comment]
The term 'overlay' in the addon means any tiled imagery applied to a terrain.
`--showOverlayOnly` means show only imagery ignoring OSM objects.

**Comment by vvoovv** [comment]
The term 'overlay' in the addon means any tiled imagery applied to a terrain. `--showOverlayOnly` means "show imagery only" ignoring OSM objects.

**Comment by polarkernel** [comment]
> The term 'overlay' in the addon means any tiled imagery applied to a terrain. --showOverlayOnly means "show imagery only" ignoring OSM objects.

I see, then I used the wrong term. What I wanted is that in all three cases
1) OSM objects only
2) OSM objects and satellite imagery
3) Satellite imagery only

I am able to draw intersection and way-section polygons from within my code for debugging and for the customization of way-widths and intersection radii. So for the case 3., OSM objects should not be rendered, but `plt.show()` for the figure should not yet be called. Don't know if this is feasible.

**Comment by vvoovv** [comment]
I guess 1. and 2. work for you. Right?

To get 3. use the options for 2. and add the argument _--showOverlayOnly_. Please let me know if it works for you this way.

**Comment by polarkernel** [comment]
> I guess 1. and 2. work for you. Right?

Yes.

> To get 3. use the options for 2. and add the argument --showOverlayOnly.  Please let me know if it works for you this way.

No. This way, only the satellite image is displayed, but none of my streets. But don't waste more time, I can work with option 2. The satellite image is of limited help because unexpectedly many of the roads are deep in shadow and almost invisible. Maybe I need to search for towns that are close to the equator or that have only small buildings.

**Comment by vvoovv** [comment]
> 3. Satellite imagery only

> No. This way, only the satellite image is displayed, but none of my streets. 

Sorry, there is probably some misunderstanding. The goal for 3. is to display nothing but the satellite imagery. Right?

**Comment by vvoovv** [comment]
I am going to check if orthophoto imagery can be used.

**Comment by polarkernel** [comment]
> Sorry, there is probably some misunderstanding. The goal for 3. is to display nothing but the satellite imagery. Right?

No, I like to have the satellite image as in 2., but no OSM objects (buildings, grassland, etc.), however I need the streets and intersections or whatever else that I draw during the execution of my code using `plt.plot()` painted over the satellite image. For 1. and 2., these drawings appear, but not for 3.

**Comment by vvoovv** [comment]
> I am going to check if orthophoto imagery can be used.

It should work at least for for _streets/rotterdam_01.osm_. But I need to fix a minor bug first. I am fixing it right now.

**Comment by vvoovv** [comment]
Committed the fix.

Instead of `--overlayType arcgis-satellite --overlayAccessToken .. ` use -`-overlayType custom --overlayUrl https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0/Actueel_ortho25/EPSG:3857/{z}/{x}/{y}.jpeg` for _streets/rotterdam_01.osm_.

Is it orthophoto imagery better than ArcGIS or Mapbox? I'll try to find the one for _berlin_karl_marx_allee.osm_.

**Comment by polarkernel** [comment]
I get an error for the first tile:

```
Preparing overlay for import...
(1 of 70) Downloading the tile image https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0/Actueel_ortho25/EPSG:3857/19/268639/173368.jpeg
```

![error](https://user-images.githubusercontent.com/48180714/168436731-8b5bafaa-8aab-4bc2-bf3b-b2419957fa47.png)

**Comment by vvoovv** [comment]
Sorry, forgot to push to the origin. Please try it again.

**Comment by polarkernel** [comment]
Now it works fine! Yes, these images are better for this task. Can even find OSM operator's errors:

![Namenlos](https://user-images.githubusercontent.com/48180714/168439579-b3fa19c4-02b2-4dce-996c-e0c4b498c4f4.png)

**Comment by vvoovv** [comment]
>I'll try to find the one for _berlin_karl_marx_allee.osm_.

The orthophotos for Berlin aren't available in the needed projection.

**Comment by polarkernel** [comment]
I looked at the backgrounds in JOSM. The best quality and resolution there (for Berlin) are ESRI aerial images. I found [some code](https://community.esri.com/t5/arcgis-enterprise-questions/export-tiles-from-esri-service-to-tile-package/td-p/571767) on how to get tiles from there using _arcgis_. Seems to require a token, but I don't know if it is free.

**Comment by vvoovv** [comment]
> No, I like to have the satellite image as in 2., but no OSM objects (buildings, grassland, etc.), however I need the streets and intersections or whatever else that I draw during the execution of my code using `plt.plot()` painted over the satellite image. For 1. and 2., these drawings appear, but not for 3.

Omit the argument `--buildings` to omit buildings. The problem is I can't test it in the branch _streets_intersections_, since the set of arguments that work in the branch _dev_ does't work in the branch _streets_intersections_.

**Comment by vvoovv** [comment]
> I looked at the backgrounds in JOSM. The best quality and resolution there (for Berlin) are ESRI aerial images. I found [some code](https://community.esri.com/t5/arcgis-enterprise-questions/export-tiles-from-esri-service-to-tile-package/td-p/571767) on how to get tiles from there using _arcgis_. Seems to require a token, but I don't know if it is free.

Is it really different from `--overlayType arcgis-satellite`?

**Comment by polarkernel** [comment]
> The problem is I can't test it in the branch streets_intersections, since the set of arguments that work in the branch dev does't work in the branch streets_intersections.

Just replace `--roadPolygons` by `--roadIntersections`.

> Omit the argument --buildings to omit buildings.

This is helpful. Please stop further developments, now I am happy with what I currently have.

**Comment by polarkernel** [comment]
> Is it really different from --overlayType arcgis-satellite?

No, the images are identical. Don't know why I got this impression. Meanwhile, I found it helpful to use StreetMap to get a closer look for cases, where I am not clear from the satellite image.

**Comment by vvoovv** [comment]
> The problem is I can't test it in the branch _streets_intersections_, since the set of arguments that work in the branch _dev_ does't work in the branch _streets_intersections_.

Namely, this command doesn't work in the branch _streets_intersection_ while it works in _dev_:
```
python.exe -m script.command_line --buildings --highways --detectFeatures --simplifyPolygons --classifyFacades --setupScript setup\mpl_blosm.py --osmFilepath ..\osm_extracts\facade_visibility\manhattan_01.osm
```

**Comment by polarkernel** [comment]
> Namely, this command doesn't work in the branch streets_intersection while it works in dev:

I can't yet get the reason. I assume there is something different with the `WayManager`. Using the command line that you mention, for the branch _streets_intersection_, my program crashes at the line [99](https://github.com/prochitecture/blosm/blob/7f71d7d296ca62c8546eee15ca63f7027a42b859/action/facade_visibility.py#L99) in _facade_visibility.py_. It seems that the object `way `has no attribute `segments`.

In the branch _streets_graph_cycles_ and also in _streets_intersections_, the ways are accessed by the method `getAllWays()`, while in _dev_ the method `getFacadeVisibilityWays()` is used. But this can't make the difference, as only the selected tags are different.

There is a difference in the setup of the `WayManager` in _mpl_blosm.py_ since the branch _streets_graph_cycles_. In _dev_, it was created by `wayManager = setup.getWayManager()`, while since the new branches, `wayManager = WayManager(osm, app)` is used. Additionally, in the new setups several conditions of the form 

```Python
        osm.addCondition(
            lambda tags, e: tags.get("highway") in ("primary", "primary_link"),
            "roads_primary",
            wayManager
        )
```
have been added.

Does this information mean anything to you?

**Comment by polarkernel** [comment]
> Namely, this command doesn't work in the branch _streets_intersection_ while it works in dev:

I was able to localize this bug more precisely. In the branch _streets_intersection_, file _app/__init__.py_ at line [159](https://github.com/prochitecture/blosm/blob/7f71d7d296ca62c8546eee15ca63f7027a42b859/app/__init__.py#L159), the order of the managers to be processed is 

1. `WayManager`
2. `RoadPolygonsManager`

when used for road polygons or intersection commands. But when the commands for the branch _dev_ are used, this order is

1. `BaseBuildingManager`
2. `WayManager`

One of the actions in `BaseBuildingManager` calls `do()` in `FacadeVisibility`, where ways from `WayManager` are already used. But there, the `WayManager` object is not yet completely initialized, which leads to the crash.

I could not find where these orders are defined, but I think, now you will be able to help.

**Comment by vvoovv** [comment]
This finding must be helpful. I'll take a look.

**Comment by vvoovv** [comment]
I moved the call of `WayManager(..)` before the one of `BaseBuildingManager(..)`. The command from the [message](#issuecomment-1126783178) works for me without any errors if I comment out the line 24:
```python
from action.road_intersections import RoadIntersections
```

There is import of _cv2_ library in the module _action.road_intersections_. What OpenCV is used for?

**Comment by polarkernel** [comment]
> I moved the call of WayManager(..) before the one of BaseBuildingManager(..).

Thanks, works for me too now.

> There is import of cv2 library in the module action.road_intersections. What OpenCV is used for?

It isn't used there and was never. This is an example of an unpleasant feature of my development environment (VS Code). If I accidentally click on a word suggested by autocompletion, then the editor automatically ensures that the associated library is imported. I then remove the autocompleted word, but if this library is installed in my interpreter, I don't perceive this import statement. I committed the corrected code.

**Comment by vvoovv** [comment]
Tiles are cached by the addon. Once they are cached, the attribute `--overlayAccessToken` can be omitted.

**Comment by polarkernel** [comment]
Today, I also tested the import using `--overlayType mapbox-satellite`. Works perfect!! I got the impression that geometrically, the OSM data fits better to this imagery than to `arcgis-satellite`. But I may be wrong. At least, sometimes the shadows of the buildings are different, which makes other parts more visible. Very helpful.
