### ISSUE TITLE
Distance of the way's centerline from the left border of the cluster is always zero

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#47]
There is a bug in _action/generate_streets.py_, line 590: distance of the way's centerline from the left border of the cluster is always zero.

On a different note. I'd prefer to have an offset from the cluster's centerline instead of the distance from the left border of the cluster.

**Comment by polarkernel** [comment]
> There is a bug in action/generate_streets.py, line 590: distance of the way's centerline from the left border of the cluster is always zero.

Maybe the line numbers have changed. At line 590, the trim-value of an object is adjusted, and it is almost never zero. Could you please point me to the correct line number?

> On a different note. I'd prefer to have an offset from the cluster's centerline instead of the distance from the left border of the cluster.

I will implement this together with the above bug fix.

**Comment by vvoovv** [comment]
Sorry, I made a commit yesterday that changed the line.

Before it was in the line [590](https://github.com/prochitecture/blosm/blob/8177bf16d2e3cbe27c2baf9a1e3d17432dd5864c/action/generate_streets.py#L590).
Now it's in the line [622](https://github.com/prochitecture/blosm/blob/15d67a18c61deabec01ada4af7cc063693c75541/action/generate_streets.py#L622).

**Comment by polarkernel** [comment]
> I'd prefer to have an offset from the cluster's centerline ...

Implemented and committed. The `offset` in the class `TrimmedWaySection` is negative, when the way's centerline is left of the cluster's centerline.
