### ISSUE TITLE
Mark dead-ended street-sections or cluster

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#48]
I am currently experimenting with creating terrain patches between streets:
![image](https://user-images.githubusercontent.com/613295/216768997-5be5a92d-53e9-437f-8d22-1240910f483b.png)

I need to know that one or both ends of a street-section or a cluster is dead-ended.

I suggest adding the following properties to the classes `TrimmedWaySection` and `WayCluster`:
* `startConnected` (True or False)
* `endConnected` (True or False)

**Comment by polarkernel** [comment]
> I suggest adding the following properties to the classes `TrimmedWaySection `and `WayCluster`.

This feature is implemented and committed.

**Comment by vvoovv** [comment]
Now the terrain patches look much better if not #49.
Also borders for the area of interest are needed. I'll create a separate issue for the borders.

![image](https://user-images.githubusercontent.com/613295/217115186-63d16c9b-4386-43a1-a136-eaae8a19ec10.png)
