### ISSUE TITLE
Weird geometry in the intersections

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#49]
Can you reproduce it?

![image](https://user-images.githubusercontent.com/613295/217111802-328254da-eeab-4cf2-8bc3-0a9eb434f779.png)

![image](https://user-images.githubusercontent.com/613295/217112578-308f7256-5e3c-4433-a72e-8d10016219b0.png)

**Comment by polarkernel** [comment]
> Can you reproduce it?

Yes. I was not able to find this bug in a reasonable amount of time. So for now, I have reverted the `createLongClusterWays()` process to the old version with only two ways per cluster. This change is committed.

I am currently refactoring all the processes that follow `createLongClusterWays()` anyway. These changes are needed to implement the version with more than two ways in a cluster, and also to add clusters that need to be clipped to solve problems like [this](https://github.com/prochitecture/blosm/issues/44#issuecomment-1412061512). The latter does not fit into the existing concept at all. In the end, I will come back with a solution that no longer produces weird intersection geometries (I hope).
