### ISSUE TITLE
An IntersectionArea has a key in self.connectors which is not available in the dictionary waySectionLines

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#51]
One of the instances of `IntersectionArea` has a connector to the street segment with id=_1066_. However the key _1066_ is not availabe in the dictionary `waySectionLines`.

**Comment by polarkernel** [comment]
I am close to committing the next release with a lot of new or refactored code. I will check for this bug before submitting it. Hopefully this will happen this weekend.

**Comment by polarkernel** [comment]
This bug should be fixed by the last committed version.

**Comment by vvoovv** [comment]
Thanks, the error disappeared.

I also removed the line `from osmPlot import *` from _lib/CompGeom/clipParallelPart.py_.

**Comment by vvoovv** [comment]
The centerline of the new cluster gives a weird geometry when offseting the centerline. Some straightening would be required.

![image](https://user-images.githubusercontent.com/613295/219904829-fb01dadb-8268-4210-b6b9-8899a84e5ad7.png)


![image](https://user-images.githubusercontent.com/613295/219904525-22636d75-b10e-4f45-9a74-2ac8326fbee7.png)

![image](https://user-images.githubusercontent.com/613295/219904815-75574732-2bd6-4ca5-8a55-0439858dc2f4.png)

**Comment by polarkernel** [comment]
> The centerline of the new cluster gives a weird geometry when offseting the centerline. Some straightening would be required.

Fixed and committed. There are two effects that required this simplification. First, line expanding algorithms all have problems with short end tails. Even _PyGeos_ can't handle them properly. Second, the centerline algorithms that use triangulation have a tendency to produce zigzag lines, I found several reports about this. Here is an example where this is clearly visible:

<img src="https://user-images.githubusercontent.com/48180714/219959648-4a2906fd-9097-433d-a9d5-01d9fe933461.png" width="400">

**Comment by vvoovv** [comment]
> Fixed and committed.

What was the idea behind this fix?

**Comment by vvoovv** [comment]
There area now inconsistencies in data describing connectors of intersections. Those inconsistencies lead to weird geometry of the terrain patches.

For example, take an element with the index _20_ in the list `intersectionAreas`.
It has:
```python
self.connectors = {
    '198': (0, 'S'),
    '192': (1, 'E')
}
self.clusterConns = {
    '32': (0, 'E', -1)
}
```

One can see that there are 2 connectors starting in the intersection vertex with the same index _0_.

**Comment by polarkernel** [comment]
> There area now inconsistencies in data describing connectors of intersections.

Bug fixed and committed.

**Comment by polarkernel** [comment]
> What was the idea behind this fix?

The main part of the fix is to disallow short segments at the end of a center line. This is due to the inability of almost all line offsetting algorithms to correctly handle large offset distances with short segments at the end of the line. Let me try to explain the reason. In the images below, the black line is the centerline with a short, slightly angled segment at the end. With a short offset, as depicted on the left, it is no problem to construct the offset line. I marked the last vertex of the offset line by a red dot. But if the offset distance is large compared to the length of the last segment, as shown on the right, then the last vertex (red dot) is behind the end of the line. This situation may occasionally arise with clusters.

<img src="https://user-images.githubusercontent.com/48180714/220076884-c9a8e7c3-5177-4733-ac4c-90241ffa4780.png" width="600">

Almost all libraries (shapely, pyGeos, ...) have difficulties to solve such situations properly in general cases. My fix removes vertices, that are closer than 10 m to the end of the cluster centerlines. It is very unlikely that a cluster-way would make a bend so close to an intersection. Additionally, I introduced a simplification of the centerlines by a Ramer-Douglas-Peucker algorithm with a gentle tolerance parameter. For the current scene, this would not be required, but it helps to smooth eventual triangulation artifacts. Since there are only a few clusters in a scene, I took the liberty of accepting this additional computation expense.

**Comment by vvoovv** [comment]
> Bug fixed and committed.

Thanks. There are still problems with the terrain patches. I'll trace them down.

**Comment by vvoovv** [comment]
Found the problem.

`wayClusters[32]`: `startConnected` and `endConnected` aren't set (equal to _None_). That is equivalent of setting them to _False_ (i.e. the ends of the cluster are dead-ended). But they are actually connected to the intersections.

**Comment by vvoovv** [comment]
More issues.

`intersectionAreas[0]`

![image](https://user-images.githubusercontent.com/613295/220210438-f33491d5-e6c3-4c82-9ebd-13711d613101.png)

First, the order of vertices in `intersectionAreas[0].polygon` is wrong (must be counterclockwise)

Second. `intersectionAreas[0].clusterConns` is equal to
```python
{
    '40': (1, 'E', -1),
    '41': (3, 'S', -1)
}
```
However the upper connector starts with the vertex with the index _0_ and the lower connector starts with the vertex with the index _2_. That's under the clockwise order as it is the case now for this intersection polygon.

**Comment by polarkernel** [comment]
> Found the problem.
More issues.

Both bugs fixed and code committed. The problem with `startConnected` and `endConnected` was caused by an error in conflict resolution during the big update, sorry.

**Comment by vvoovv** [comment]
`intersectionAreas[3].polygon` has a duplicated point _(420.3545, -181.1162)_ with the indices _1_ and _2_. Is it a bug or a really short edge in the polygon?

**Comment by vvoovv** [comment]
There area more problems related to `intersectionAreas[3]`. It has
```python
clusterConns = {
    9: (3, 'E', -1),
    8: (5, 'S', -1)
}
connectors = {
    78: (0, 'E')
}
```
Actually `wayClusters[9]` is connected to `intersectionAreas[3]` with its start. The letter _'E'_ is wrong in the dictionary.
Also `wayClusters[9].startConnected` is equal to _False_, but it should be _True_.

Actually `wayClusters[8]` is connected to `intersectionAreas[3]` with its end. The letter _'S'_ is wrong in the dictionary.
Also `wayClusters[8].endConnected` is equal to _False_, but it should be _True_.

Finally, the part connecting `waySectionLines[78]` and `intersectionAreas[3]` is missing as shown on the image below:
![image](https://user-images.githubusercontent.com/613295/220486182-d36dacf4-5ee5-474c-a7b2-87331e114d6a.png)

**Comment by polarkernel** [comment]
> intersectionAreas[3].polygon has a duplicated point (420.3545, -181.1162) with the indices 1 and 2. Is it a bug or a really short edge in the polygon?

This was a bug. It happened, when the way-section to intersect with a cluster was exactly perpendicular to the cluster, as for example shown in the image at the right:

<img src="https://user-images.githubusercontent.com/48180714/220580417-c7b1857f-7fb6-4605-8dd8-b6845849fd92.png" width="600">

> There are more problems related to intersectionAreas[3]

All fixed. New code is committed.

**Comment by vvoovv** [comment]
> All fixed. New code is committed.
Thanks!

Terrain patches look fine now:

![image](https://user-images.githubusercontent.com/613295/220703520-88747dac-a9f8-4b15-bd06-3ca888a69efb.png)

![image](https://user-images.githubusercontent.com/613295/220703696-80f4598f-e93f-41db-ad82-911b25c0ee11.png)

**Comment by vvoovv** [comment]
I will continue to work on the generation of sidewalks and terrain patches when the sidewalks are present.
