### ISSUE TITLE
Strange shape of some intersections after the latest commit

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#60]
**berlin_karl_marx_allee.osm**

manager.intersectionAreas[62]:
![image](https://user-images.githubusercontent.com/613295/234878038-db81ec5c-e223-4548-99f4-9dcd07c96141.png)

manager.intersectionAreas[26]
![image](https://user-images.githubusercontent.com/613295/234879362-3b936b1b-5c81-4f69-a34d-5cbda49dbc03.png)

**Comment by polarkernel** [comment]
Stupid mistake, fixed and committed, sorry.

**Comment by vvoovv** [comment]
Thanks.
