### ISSUE TITLE
Negate offset?

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#61]
`manager.streetSections[27].offset` is equal to 1.35.

Shouldn't it be negated in order for the street section to be placed correctly?

![image](https://github.com/prochitecture/blosm/assets/613295/d803c686-190d-4c54-9ec0-b8cc0456e73e)

**Comment by polarkernel** [comment]
> Shouldn't it be negated in order for the street section to be placed correctly?

I didn't negate the offsets, I made them dependent on the side of the transition for my drawings. I will correct that and make the offset positive when the turn is to the right and negative when the turn is to the left.

**Comment by polarkernel** [comment]
> I will correct that and make the offset positive when the turn is to the right and negative when the turn is to the left.

A version with signed offset as described is committed. Another [issue](https://github.com/prochitecture/blosm/issues/62#issue-1712244025) has been discovered that has not yet been fixed. Fixed some other bugs.

**Comment by vvoovv** [comment]
Thanks
