### ISSUE TITLE
Is this tagging correct?

### ISSUE THREAD

**Issue by polarkernel** [prochitecture/blosm#62]
The tagging of two ways in _berlin_karl_marx_allee.osm_ (near roundabout) irritates my algorithm:

<img src="https://github.com/prochitecture/blosm/assets/48180714/c163d99b-a0fc-4dbf-ad76-fd73b501c192" width="450">

Shouldn't the upper way-section be tagged as `merge_to_left`?

**Comment by vvoovv** [comment]
> Shouldn't the upper way-section be tagged as `merge_to_left`?

It should have been tagged as `merge_to_left` if there were a marking on the related marking. But there is no any markings as I checked on the satellite imagery.

The tags `merge_to_left` or `merge_to_right` can be assumed in the case when the number of lanes is changed and the tag `turn:lanes` is missing. I suggest to assume the tag `merge_to_left` for now in those cases.

**Comment by polarkernel** [comment]
Solved, see issue #64.
