### ISSUE TITLE
Error for the dataset husum_altstadt.osm

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#7]
File "blender-osm\action\facade_visibility.py", line 168, in calculateFacadeVisibility
    x2 = intersections[i+1][1] * segmentLength/2.
IndexError: list index out of range

**Comment by polarkernel** [comment]
> File "blender-osm\action\facade_visibility.py", line 168, in calculateFacadeVisibility
x2 = intersections[i+1][1] * segmentLength/2.
IndexError: list index out of range

This is the error that occurs, when a building has skipped edges, so that the number of intersections of the building with the way-segment axis gets odd. But I don't get this error. I am using GitHub commit 9bfa7a3 on _dev_.

**Comment by vvoovv** [comment]
Strange...
Yes it's the latest commit.

**Comment by vvoovv** [comment]
Did you use the file https://github.com/prochitecture/osm_extracts/blob/master/facade_visibility/husum_altstadt.osm ?

**Comment by polarkernel** [comment]
Yes. Here is what I get:

![4](https://user-images.githubusercontent.com/48180714/115554857-365d6900-a2af-11eb-88dc-46a1b40ef0dd.png)

**Comment by vvoovv** [comment]
Here is the building that causes the error:
https://www.openstreetmap.org/way/723815515

**Comment by vvoovv** [comment]
Which version of Python do you use?

**Comment by vvoovv** [comment]
My version of Python is 3.7.0

**Comment by vvoovv** [comment]
Tried it with Python 3.8.2 and got the same error.

**Comment by polarkernel** [comment]
It runs correctly with Python 3.6.6 64-bit, but I get this error with Python 3.8.3 32-bit. But maybe also the versions of numpy for instance may have an influence. On my systems, the numpy versions are

Python 3.6.6 it is 1.19.2
Python 3.8.3 it is 1.18.5

Anyway, I'll check what's going on using Python 3.8.3.

**Comment by vvoovv** [comment]
Numpy has the following versions at my computer:
Python 3.7.0: 1.20.1
Python 3.8.2: 1.20.2

**Comment by polarkernel** [comment]
> File "blender-osm\action\facade_visibility.py", line 168, in calculateFacadeVisibility
x2 = intersections[i+1][1] * segmentLength/2.
IndexError: list index out of range

I found the reason for this error.  The [building ](https://www.openstreetmap.org/way/723815515), that causes the error,  is crossed by a way segment, that passes exactly through a vertice of the building's contour:

<img src="https://user-images.githubusercontent.com/48180714/115713227-0f1d9f00-a376-11eb-9d17-555634026521.png" width="400">

This produced two intersections by the two edges that are connected to this vertice, but only one dummy edge is required to start there. Removing duplicates of the intersection's x-values fixed this issue. The solution is committed to the _dev_ branch on _blosm_. It remains a miracle why this didn't happen with all Python versions, I couldn't catch the reason. But I hope the solution runs also with your versions.

By the way, the new version of the renderer is amazing!

**Comment by vvoovv** [comment]
Yes, it works for me now
