### ISSUE TITLE
Wrong order of street-sections

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#70]
_streets/container_terminal_hamburg.osm_

The problem occurs in the only road with the category _unclassified_ and multiple lanes and side lane transitions.

OSM-ids for the segments of that road are shown below:

![image](https://github.com/prochitecture/blosm/assets/613295/19d3d163-2803-467d-b6ff-9caa46d91b17)

662064480
662064487
662064493

If take the `StreetSegment` for `osmId=662064480`, it has an instance of `TransitionSideLane` in the attribute `start`. To get the incoming street section, we use the following expression:
```python
ways = section.start.ways
incomingStreetSection = manager.waySectionLines[-ways[0] if ways[0]<0 else -ways[1]]
```
`incomingStreetSection` has `osmId=662064493`, which is not correct.

We if get the incoming street section for `incomingStreetSection` with `osmId=662064493`, we will get again the street section with `osmId=662064493` (i.e. an endless cycle).

**Comment by polarkernel** [comment]
> The problem occurs in the only road with the category unclassified and multiple lanes and side lane transitions.

Should be fixed for the general case. New code is committed.

**Comment by vvoovv** [comment]
It looks like that something is wrong with the offset. The section with 5 lane is gray, since I didn't prepare a texture for 5 lanes.

![image](https://github.com/prochitecture/blosm/assets/613295/ccf55a82-42dd-4f56-9d62-9aa4432b1f17)

**Comment by polarkernel** [comment]
> It looks like that something is wrong with the offset.

Fixed and committed.

**Comment by vvoovv** [comment]
Thanks
