### ISSUE TITLE
Floating point precision errors

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#77]
I'd like to raise a concern about floating point precision errors caused by Blender data structures (`Vector`, `Quaternion` from `mathutils`).

Internally Blender uses single precision 32 bits format for floating point variables, while Python uses double precision 64 bits one.

Those error are quite noticeable for large numbers:
```python
>>> Vector([1266364.1409105703, -4293659.691863989, 4528076.270102509])
Vector((1266364.125, -4293659.5, 4528076.5))
```

The precision errors may matter for small numbers as well.

How did you deal with those errors in different parts of the addon?

**Comment by polarkernel** [comment]
> How did you deal with those errors in different parts of the addon?

In most cases, the structures from `mathutils` are replaced by Python structures wherever geometric computations need to be done. From my observations, very often the errors increase when two numbers of almost the same size are subtracted. If these situations can be avoided, the errors are lower. The order of operations also plays an important role. However, I am not familiar enough with numerical mathematics, so I opted for the greater floating-point precision within Python. Structures from `mathutils` are only used in static cases (e.g. as key for a position in a dictionary) and as transfer structures between my modules and the rest of the addon.
