### ISSUE TITLE
manager.waySectionLines is empty

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#79]
I want to generate the streets on facade_visibility/berlin_karl_marx_allee.osm.

I found out that _manager.waySectionLine_ was empty. Were there recent changes that caused that issue?

**Comment by polarkernel** [comment]
> I found out that manager.waySectionLine was empty. Were there recent changes that caused that issue?

Yes, I started the major redesign for the new ideas and structures. Please go back to the tag `streets_for_gn`, then you have the old version (see [here](https://github.com/prochitecture/blosm/issues/72#issuecomment-1848920344)).

**Comment by vvoovv** [comment]
Ok, got it.
