### ISSUE TITLE
Inconsistency in the returned data (berlin_karl_marx_allee.osm)

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#91]
![image](https://github.com/prochitecture/blosm/assets/613295/4442da82-fcb2-4067-bd99-2ad5f24d8ded)

OSM-Id of the first section along the direction of movement is `316869461`
OSM-Id of the second section along the direction of movement is `316869459`.

In the returned data structures:
```python
street.tail.tags["id"] == "316869461" # OSM-Id of the FIRST section
street.head.tags["id"] == "316869459" # OSM-Id of the SECOND section
```

_____

![image](https://github.com/prochitecture/blosm/assets/613295/d95694eb-4d97-4d0d-a80b-c54919e00c21)

OSM-Id of the first section along the direction of movement is `303406976`
OSM-Id of the second section along the direction of movement is `302694753`.

```python
street.tail.tags["id"] == "302694753" # OSM-Id of the SECOND section
street.head.tags["id"] == "303406976" # OSM-Id of the FIRST section
```

**Comment by polarkernel** [comment]
Bug fixed and committed. It was sluggish to find, but easy to fix.

**Comment by vvoovv** [comment]
Unfortunately, the problem persists. The values in the above examples were simply swapped.

Now:

The first example:
```python
street.tail.tags["id"] == "316869459" # OSM-Id of the SECOND section
street.head.tags["id"] == "316869461" # OSM-Id of the FIRST section
```

The second example:
``` python
street.tail.tags["id"] == "303406976" # OSM-Id of the FIRST section
street.head.tags["id"] == "302694753" # OSM-Id of the SECOND section
```

**Comment by polarkernel** [comment]
Fixed and committed. The real reason was deeper, and the last fix was just symptom treatment. Sorry.

**Comment by vvoovv** [comment]
I've got again the result from the [first message](#issue-2255259531).

In addition something got wrong with styling. I guess it could be cause by the recent deletion of the line `street.setStyle(streetStyle)` at _action/generate_streets.py_.

**Comment by polarkernel** [comment]
> I've got again the result from the [first message](https://github.com/prochitecture/blosm/issues/91#issue-2255259531).

This should be finally fixed (and committed). Here what I get for your examples:
```Python
street.head.tags['id']
'316869461'
street.head.succ.succ.tags['id']
'316869459'

street.head.tags['id']
'303406976'
street.head.succ.succ.tags['id']
'302694753'
```
> In addition something got wrong with styling. I guess it could be cause by the recent deletion of the line street.setStyle(streetStyle) at action/generate_streets.py.

I can't find any issues with this deleted code. In my opinion, this was necessary. Can you tell me more details about the problem?

By the way, all way-items have an ID, which is easier for me to identify. The first example above becomes:
```Python
street.id
503
street.head.id
126
street.head.succ.succ.id
115
```
When you plot the scene in script mode, you get all these IDs. For the streets, you get the combination (street id)/(section id), so for the example above 503/126 and 503/115:

<img src="https://github.com/prochitecture/blosm/assets/48180714/2097905d-4f44-4588-afe8-a561ec970fc1" width="400">

**Comment by vvoovv** [comment]
> This should be finally fixed (and committed). 

Thanks. I'll create separate tickets for the other issues.
