### ISSUE TITLE
Street sections with an offset don't fit intersections

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#92]
berlin_karl_marx_allee.osm

street.id ==503
section.id == 115

![image](https://github.com/prochitecture/blosm/assets/613295/de92bea9-e5b3-48dd-89c7-64d795307472)

After applying an offset:

![image](https://github.com/prochitecture/blosm/assets/613295/f47f459e-61ea-40a2-9e01-6630604d4a3e)

The same problem for:
street.id ==502
section.id == 109

**Comment by polarkernel** [comment]
Fixed and committed:

![1](https://github.com/prochitecture/blosm/assets/48180714/f86a34db-d08d-4adc-bacb-d514405ae7fe)

**Comment by vvoovv** [comment]
Thanks
