### ISSUE TITLE
A problem with a style block assignment

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#93]
A correct style block is not assigned anymore after the [commit](https://github.com/prochitecture/blosm/commit/bb901f002b581bf3099400f35d3aced92a3b9e88).

I guess it's due to the fact that the attribute `oneway` and the other ones are not set by the time of the style block assignment.

**Comment by polarkernel** [comment]
To compute the attribute `oneway` and the others, the attributes `nrLanes` and `laneWidth` are required (for the function `lanePattern`). So we had to construct a `street` from the section, get `streetStyle` for it and set it as style. Now the attributes `nrLanes` and `laneWidth` are available through `getStyleBlockAttr`, can be used by `lanePattern` and the results are set directly in the `section` within the `street`. But this does not update the style of `street`, you are right.

My question is: If I were to request the `streetStyle` from `street` again at this stage and set it to `street`, would the style then be correct, as the attributes of the `section` inside are completed now?

The way it was done before the commit is not correct. It constructs a new `Street` instance from the old `section` instance in `street` and sets its style.  The old instance `street` then remains unused.

**Comment by polarkernel** [comment]
I committed this suggestion along with another bugfix. Hopefully this fixes the problem.

**Comment by vvoovv** [comment]
> To compute the attribute `oneway` and the others, the attributes `nrLanes` and `laneWidth` are required (for the function `lanePattern`).

Aren't the attributes `oneway`, `forwardLanes`, `backwardLanes` calculated in the function `laneWidth`?
I thought a street style wasn't needed to set set those parameters.

**Comment by polarkernel** [comment]
There is no function `laneWidth`? I thought, the width of a lane (Issue #67) and also the default number of lanes should be defined from the PML styles. This is only possible by requesting a style.

**Comment by vvoovv** [comment]
I meant the function `lanePattern`.

I split the process of setting a style block for a street and its items into parts. First, a style block (basically, the default values for the number of lanes and the lane width) is set for the street. Then, after calling the function `lanePattern`, a style block is set for the items of the street. The code is committed.
