### ISSUE TITLE
Question: Are the attributes succ and pred already set by the call of street.setStyleForItems(streetStyle)?

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#95]
Are the attributes `succ` and `pred` already set by the call of `street.setStyleForItems(streetStyle)` in the line 509 of the module _action/generate_streets.py_?

**Comment by polarkernel** [comment]
> Are the attributes succ and pred already set by the call of street.setStyleForItems(streetStyle) in the line 509 of the module action/generate_streets.py?

No, not yet. At this stage, the streets are connected to empty (unprocessed) `Intersections`, that do not yet have an `IntConnector`, as required for intersections. The links are set later in the method `updateIntersections`, or, in rare cases, by `createSymSideLanes`. They can also be changed to `Crosswalks`, `Corners`, `PtStops` later, once we implement these.

It would be possible to link them to these empty `Intersection` objects before the call to `street.setStyleForItems(streetStyle)`, but I do not know if this would make any sense.

**Comment by vvoovv** [comment]
I wanted to have a style for `SideLane`s. But it is seemingly not set in the function `street.setStyleForItems(streetStyle)`. Since the attributes `succ` and `pred` are not yet set.

Can the call `street.setStyleForItems(streetStyle)` be made later in the code when `succ` and `pred` are already set?

**Comment by polarkernel** [comment]
> Can the call `street.setStyleForItems(streetStyle)` be made later in the code when `succ` and `pred` are already set?

I have moved this call to the end of the method `finalizeOutput` ([line 1994](https://github.com/prochitecture/blosm/blob/a2831316c73da1d93337692ed5f375922c2efa7b/action/generate_streets.py#L1994)), which is the last method called in `generate_streets`. I assume that it is correct to combine it with a preceding call to `styleStore.get`:
```python
                streetStyle = self.styleStore.get( self.getStyle(street) )
                street.setStyleForItems(streetStyle)
```
This code is committed.

**Comment by vvoovv** [comment]
I added an optimization.

A `style` is set as an attribute of a `street` (`street.style`) in the method `createEmptyWaymap`. However later in the method `finalizeOutput` it turns out that there are instances of the class `Street` without the the attribute `style`. How can that happen?

**Comment by polarkernel** [comment]
> However later in the method `finalizeOutput` it turns out that there are instances of the class `Street` without the the attribute `style`. How can that happen?

To insert a `SideLane` or a `SymLane` into a `Street`, two instances of `Street`, each storing only one `Section` had to be removed and be replaced by a `Street` containing the sections and the transition object linked as a list. I forgot to update the style of this new `Street`. This is now fixed in the method `createSymSideLanes`.

To be on the safe side, we might leave your fix in place.

**Comment by vvoovv** [comment]
> To be on the safe side, we might leave your fix in place.

I commented the fix out to catch similar cases in the future.
