### ISSUE TITLE
Question: pred-succ vs incoming-outgoing in the class SideLane

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#96]
Aren't they duplicate each other?

**Comment by polarkernel** [comment]
> Aren't they duplicate each other?

You are right. Incoming-outgoing was just easier to understand for the construction. Using my editor I can easily replace them to pred-succ, if that is important. In a few years, I will anyway struggle to understand what my idea was, in either case.

**Comment by vvoovv** [comment]
I suggest leaving only pred-succ.

**Comment by polarkernel** [comment]
> I suggest leaving only pred-succ.

Replaced incoming-outgoing and committed.

**Comment by vvoovv** [comment]
Thanks
